<a href="https://colab.research.google.com/github/fatimazain118/Python-for-Data-Science/blob/main/NumPyyy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#creating array
import numpy as np
l1=[10,20,30,40]
n= np.array(l1)
n

array([10, 20, 30, 40])

In [ ]:
type(n)

numpy.ndarray

In [ ]:
#creating multi-dimension array

import numpy as np
n1= np.array([(1,2,3),(4,5,6)])  #using tuple
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(n1)

numpy.ndarray

In [ ]:
n2 = np.array([[2,34,3],[2,67,8]])  #using list
n2

array([[ 2, 34,  3],
       [ 2, 67,  8]])

In [ ]:
type(n2)

numpy.ndarray

In [ ]:
n2.ndim   #checking dimensions of an array

2

In [ ]:
n.ndim

1

In [ ]:
n2.shape   #tells no. of rows and column

(2, 3)

In [ ]:
#to change the shape of an array, no. of elements remains same
n2.shape = (3,2)
n2.shape

(3, 2)

In [ ]:
n2

array([[ 2, 34],
       [ 3,  2],
       [67,  8]])

In [ ]:
#Joining NumPy arrays
#using vstack() (vertical stack)
n8 = np.array([2,3,4])
n9= np.array([2,6,7])
np.vstack((n8,n9))


array([[2, 3, 4],
       [2, 6, 7]])

In [ ]:
#hstack() horizontal stack

np.hstack((n8,n9))

array([2, 3, 4, 2, 6, 7])

In [ ]:
#column_stack()

np.column_stack((n8,n9))

array([[2, 2],
       [3, 6],
       [4, 7]])

In [ ]:
#Initializing Numpy array with zeros later we can fill to it

n3= np.zeros((2,2))
n3

array([[0., 0.],
       [0., 0.]])

In [ ]:
type(n3)

numpy.ndarray

In [ ]:
#Initializing Numpy array with same number
n4= np.full((2,2),10)   #10 will be filled in both rows and column
n4

array([[10, 10],
       [10, 10]])

In [ ]:
#Initializing NumPy array within a range
n5 = np.arange(5,11)
n5


array([ 5,  6,  7,  8,  9, 10])

In [ ]:
#to want speciafic gap between no.
n6= np.arange(2,21,2)  #table of 2
n6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#Initializing NumPy array with random numbers
n7 = np.random.randint(1,100,5)  #[1,100) tk 5 random no.
n7

array([37, 82, 98, 16, 24])

In [ ]:
#NumPy Intersection & Difference
n10 = np.array([1,2,3,4,5])
n11= np.array([3,2,4,8,9])
np.intersect1d(n10,n11)

array([2, 3, 4])

In [ ]:
np.setdiff1d(n10,n11)

array([1, 5])

In [ ]:
np.setdiff1d(n11,n10)  #n11-n10

array([8, 9])

In [ ]:
#Addition of NumPy arrays
np.sum([n10,n11])     #total sum of both array

41

In [ ]:
np.sum([n10,n11],axis = 0)  #addition with respect to column

array([ 4,  4,  7, 12, 14])

In [ ]:
np.sum([n10,n11], axis = 1)  #addition with respect to rows

array([15, 26])

In [ ]:
#NumPy Array Mathmatics

n12= np.array([10,20,30])
n12 = n12+1                 #adding 1 to all elements in the array
n12

array([11, 21, 31])

In [ ]:
p = np.array([1,2,3])
p = p*2
p

array([2, 4, 6])

In [ ]:
p=p-1
p

array([1, 3, 5])

In [ ]:
q = np.array([10,20,30])
q= q/2
q

array([ 5., 10., 15.])

In [ ]:
#NumPy math function

n13 = np.array([1,2,3,4])
np.mean(n13)

2.5

In [ ]:
n14= np.array([11,44,5,96,67,85])
np.median(n14)

55.5

In [ ]:
np.std(n14)     #standard deviation

34.644223504391356

In [ ]:
#NumPy save and Load
n15= np.array([10,20,30,40,50,60])
np.save('my_numpy',n15)

In [ ]:
n16= np.load('my_numpy.npy')  #.npy numpy array
n16

array([10, 20, 30, 40, 50, 60])